// Don't Include this rubbish anywhere 
// except for Events/EventTypes.h

#ifdef H_EVENT_TYPES
#ifdef CREATE_EVENT_TYPE 

CREATE_EVENT_TYPE(EVENT_RENDER)
CREATE_EVENT_TYPE(EVENT_RENDER_NEEDED)
CREATE_EVENT_TYPE(EVENT_RENDER_NOT_ALLOWED)
CREATE_EVENT_TYPE(EVENT_RENDER_ALLOWED)

CREATE_EVENT_TYPE(EVENT_LOOP_STOP)

CREATE_EVENT_TYPE(EVENT_SCENE_PAUSE)
CREATE_EVENT_TYPE(EVENT_SCENE_RESUME)

#endif
#endif
